-- Development seed data - OBVIOUSLY FAKE CHURCHES FOR TESTING ONLY
-- These are clearly marked as development/test data

INSERT INTO public.churches (
  name, slug, description, address, city, state, zip, latitude, longitude,
  phone, email, website, denomination, worship_style, service_times,
  ministries, languages, kids_ministry, youth_ministry, verified, featured, active
) VALUES
  (
    'Grace Demo Church (Test)',
    'grace-demo-test',
    '[DEMO DATA] A test church for development purposes. This is not a real church.',
    '123 Test Street',
    'TestCity',
    'TS',
    '12345',
    40.7128,
    -74.0060,
    '(555) 000-0001',
    'test@grace-demo.dev',
    'https://example.com',
    'Non-Denominational',
    'Contemporary',
    '[{"day": "Sunday", "time": "10:00 AM"}, {"day": "Wednesday", "time": "7:00 PM"}]'::JSONB,
    ARRAY['Community Outreach', 'Worship', 'Prayer'],
    ARRAY['English', 'Spanish'],
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    TRUE
  ),
  (
    'Hope Sample Church (Test)',
    'hope-sample-test',
    '[DEMO DATA] A sample church for development testing. Not a real location.',
    '456 Sample Ave',
    'SampleTown',
    'ST',
    '54321',
    34.0522,
    -118.2437,
    '(555) 000-0002',
    'info@hope-sample.dev',
    'https://example.com',
    'Baptist',
    'Traditional',
    '[{"day": "Sunday", "time": "11:00 AM"}]'::JSONB,
    ARRAY['Music Ministry', 'Fellowship'],
    ARRAY['English'],
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    TRUE
  ),
  (
    'New Life Test Church (Test)',
    'new-life-test',
    '[DEMO DATA] This is a test church for database validation. Development only.',
    '789 Trial Road',
    'DemoMetropolis',
    'DM',
    '99999',
    41.8781,
    -87.6298,
    '(555) 000-0003',
    'contact@newlife-test.dev',
    'https://example.com',
    'Pentecostal',
    'Contemporary Worship',
    '[{"day": "Sunday", "time": "9:00 AM"}, {"day": "Sunday", "time": "11:00 AM"}]'::JSONB,
    ARRAY['Prayer Groups', 'Discipleship'],
    ARRAY['English', 'Creole'],
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    TRUE
  ),
  (
    'Living Water Prototype Church (Test)',
    'living-water-prototype',
    '[DEMO DATA] Prototype church for feature testing. Not a real ministry.',
    '321 Beta Street',
    'Testimonialville',
    'TV',
    '88888',
    29.7604,
    -95.3698,
    '(555) 000-0004',
    'dev@livingwater-test.dev',
    'https://example.com',
    'Presbyterian',
    'Blended',
    '[{"day": "Saturday", "time": "6:00 PM"}, {"day": "Sunday", "time": "10:30 AM"}]'::JSONB,
    ARRAY['Sunday School', 'Missions'],
    ARRAY['English'],
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    TRUE
  ),
  (
    'Restoration Demo Congregation (Test)',
    'restoration-demo-congregation',
    '[DEMO DATA] Demo data for UI/UX testing. This congregation does not exist.',
    '654 Mock Lane',
    'VirtualCity',
    'VC',
    '77777',
    33.7490,
    -84.3880,
    '(555) 000-0005',
    'hello@restoration-demo.dev',
    'https://example.com',
    'Methodist',
    'Liturgical',
    '[{"day": "Sunday", "time": "8:00 AM"}, {"day": "Sunday", "time": "10:00 AM"}]'::JSONB,
    ARRAY['Community Service', 'Bible Study'],
    ARRAY['English'],
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    TRUE
  );

-- Add a few as featured for UI testing
UPDATE public.churches SET featured = TRUE WHERE slug IN ('grace-demo-test', 'hope-sample-test', 'new-life-test');
